# Generated by Django 3.2.7 on 2021-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
            ],
        ),
    ]
