# Generated by Django 3.2.7 on 2021-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='InitiativeName')),
                ('description', models.TextField(max_length=10000, verbose_name='InitiativeAbout')),
                ('address', models.CharField(max_length=300, verbose_name='InitiativeAddress')),
                ('pub_date', models.DateTimeField(verbose_name='PublicationDate')),
                ('category_name', models.CharField(max_length=50, verbose_name='CategoryName')),
                ('rating', models.IntegerField(default=0, verbose_name='InitiativeRating')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
    ]
